Try outputting to stderr during setup

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -26,6 +26,12 @@ PATH=$venv/bin:$PATH
 #    python "$buildpack/vendor/virtualenv-1.7/virtualenv.py" "$@"
 #}
 
+setup=false
+if [ "$3" == "NONE" ]; then
+    setup=true
+    echo >&2 " * Running setup"
+fi
+
 if test -e $build/bin && ! test -d $build/bin
 then
     echo >&2 " !     File bin exists and is not a directory."
@@ -34,17 +40,17 @@ fi
 
 if test -d $cache/go-$ver/go
 then
-    echo "-----> Using Go $ver"
+    echo >&2 "-----> Using Go $ver"
 else
     #rm -rf $cache/* # be sure not to build up cruft
     mkdir -p $cache/go-$ver
     cd $cache/go-$ver
-    echo    "       First download, may take several minutes"
-    echo -n "-----> Installing Go $ver..."
+    echo >&2   "       First download, may take several minutes"
+    echo >&2 -n "-----> Installing Go $ver..."
     curl -sO $url
     tar zxf $file
     rm -f $file
-    echo " done"
+    echo >&2 " done"
 fi
 
 GOROOT=$cache/go-$ver/go export GOROOT
@@ -53,18 +59,18 @@ PATH=$GOROOT/bin:$PATH
 
 if ! (which hg >/dev/null 2>&1 && which bzr >/dev/null 2>&1)
 then
-    echo -n "       Installing Virtualenv..."
+    echo >&2 -n "       Installing Virtualenv..."
     virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv 2>&1 > /dev/null 
     . $venv/bin/activate 2>&1 > /dev/null
-    echo " done"
+    echo >&2 " done"
 
-    echo -n "       Installing Mercurial..."
+    echo >&2 -n "       Installing Mercurial..."
     pip install --use-mirrors mercurial 2>&1 > /dev/null
-    echo " done"
+    echo >&2 " done"
 
-    echo -n "       Installing Bazaar..."
+    echo >&2 -n "       Installing Bazaar..."
     pip install --use-mirrors bzr 2>&1 > /dev/null
-    echo " done"
+    echo >&2 " done"
 fi
 
 if [ "$3" == "NONE" ]; then
@@ -73,10 +79,10 @@ fi
 
 if ! test -f $build/.godir
 then
-    echo >&2 " !     A .godir is required. For instructions:"
+    echo >&2 " !     A .godir is required if go sources are present. For instructions:"
     echo >&2 " !     http://mmcgrana.github.com/2012/09/getting-started-with-go-on-heroku"
     echo >&2 " !     https://www.openshift.com/kb/kb-TDOD-some-golang-instructions"
-    exit 1
+    exit 0
 fi
 
 name=$(get_godir $build/.godir)
