Start compiles Go if needed

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -32,14 +32,6 @@ then
     exit 1
 fi
 
-if ! test -f $build/.godir
-then
-    echo >&2 " !     A .godir is required. For instructions:"
-    echo >&2 " !     http://mmcgrana.github.com/2012/09/getting-started-with-go-on-heroku"
-    echo >&2 " !     https://www.openshift.com/kb/kb-TDOD-some-golang-instructions"
-    exit 1
-fi
-
 if test -d $cache/go-$ver/go
 then
     echo "-----> Using Go $ver"
@@ -73,6 +65,18 @@ then
     echo -n "       Installing Bazaar..."
     pip install --use-mirrors bzr 2>&1 > /dev/null
     echo " done"
+fi
+
+if [ "$3" == "NONE" ]; then
+    exit 0
+fi
+
+if ! test -f $build/.godir
+then
+    echo >&2 " !     A .godir is required. For instructions:"
+    echo >&2 " !     http://mmcgrana.github.com/2012/09/getting-started-with-go-on-heroku"
+    echo >&2 " !     https://www.openshift.com/kb/kb-TDOD-some-golang-instructions"
+    exit 1
 fi
 
 name=$(get_godir $build/.godir)
